const ALLOWED_CONNECTION_REQUEST_STATUS=['collab','nocollab'];
const ALLOWED_CONNECTION_REVIEW_STATUS=['accepted','ignored'];

export  {ALLOWED_CONNECTION_REQUEST_STATUS,ALLOWED_CONNECTION_REVIEW_STATUS};