const ALLOWED_CONNECTION_REQUEST_STATUS=['collab','nocollab'];
const ALLOWED_CONNECTION_REVIEW_STATUS=['accepted','ignored'];
const PUBLIC_ROUTES = ['/login', '/signup'];

export  {ALLOWED_CONNECTION_REQUEST_STATUS,ALLOWED_CONNECTION_REVIEW_STATUS,PUBLIC_ROUTES};